,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas/issues/59214,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59214/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59214/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59214/events,https://github.com/pandas-dev/pandas/pull/59214,2396715927,PR_kwDOAA0YD850wNW0,59214,Add support for NumpyExtensionArray in pd.unique(),"{'login': 'ritwizsinha', 'id': 43509699, 'node_id': 'MDQ6VXNlcjQzNTA5Njk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/43509699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ritwizsinha', 'html_url': 'https://github.com/ritwizsinha', 'followers_url': 'https://api.github.com/users/ritwizsinha/followers', 'following_url': 'https://api.github.com/users/ritwizsinha/following{/other_user}', 'gists_url': 'https://api.github.com/users/ritwizsinha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ritwizsinha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ritwizsinha/subscriptions', 'organizations_url': 'https://api.github.com/users/ritwizsinha/orgs', 'repos_url': 'https://api.github.com/users/ritwizsinha/repos', 'events_url': 'https://api.github.com/users/ritwizsinha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ritwizsinha/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-08T23:01:55Z,2024-07-09T04:57:48Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59214', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59214', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59214.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59214.patch', 'merged_at': None}","- [x] closes #59213  (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59214/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59214/timeline,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/59213,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59213/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59213/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59213/events,https://github.com/pandas-dev/pandas/issues/59213,2396591393,I_kwDOAA0YD86O2RUh,59213,BUG: pd.unique() does not accept NumpyExtensionArray,"{'login': 'mutricyl', 'id': 118692416, 'node_id': 'U_kgDOBxMaQA', 'avatar_url': 'https://avatars.githubusercontent.com/u/118692416?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mutricyl', 'html_url': 'https://github.com/mutricyl', 'followers_url': 'https://api.github.com/users/mutricyl/followers', 'following_url': 'https://api.github.com/users/mutricyl/following{/other_user}', 'gists_url': 'https://api.github.com/users/mutricyl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mutricyl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mutricyl/subscriptions', 'organizations_url': 'https://api.github.com/users/mutricyl/orgs', 'repos_url': 'https://api.github.com/users/mutricyl/repos', 'events_url': 'https://api.github.com/users/mutricyl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mutricyl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,"{'login': 'ritwizsinha', 'id': 43509699, 'node_id': 'MDQ6VXNlcjQzNTA5Njk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/43509699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ritwizsinha', 'html_url': 'https://github.com/ritwizsinha', 'followers_url': 'https://api.github.com/users/ritwizsinha/followers', 'following_url': 'https://api.github.com/users/ritwizsinha/following{/other_user}', 'gists_url': 'https://api.github.com/users/ritwizsinha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ritwizsinha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ritwizsinha/subscriptions', 'organizations_url': 'https://api.github.com/users/ritwizsinha/orgs', 'repos_url': 'https://api.github.com/users/ritwizsinha/repos', 'events_url': 'https://api.github.com/users/ritwizsinha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ritwizsinha/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'ritwizsinha', 'id': 43509699, 'node_id': 'MDQ6VXNlcjQzNTA5Njk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/43509699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ritwizsinha', 'html_url': 'https://github.com/ritwizsinha', 'followers_url': 'https://api.github.com/users/ritwizsinha/followers', 'following_url': 'https://api.github.com/users/ritwizsinha/following{/other_user}', 'gists_url': 'https://api.github.com/users/ritwizsinha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ritwizsinha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ritwizsinha/subscriptions', 'organizations_url': 'https://api.github.com/users/ritwizsinha/orgs', 'repos_url': 'https://api.github.com/users/ritwizsinha/repos', 'events_url': 'https://api.github.com/users/ritwizsinha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ritwizsinha/received_events', 'type': 'User', 'site_admin': False}]",,2,2024-07-08T21:18:03Z,2024-07-08T23:02:35Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
arr_int = pd.array([1, 2, 3]) # Int64Dtype() => ExtensionArray
arr_complex = pd.array([1+1j, 2, 3]) # NumpyEADtype('complex128') => NumpyExtensionArray

pd.unique(arr_int)  # OK
pd.unique(arr_complex)  # NOK: TypeError: unique requires a Series, Index, ExtensionArray, or np.ndarray, got NumpyExtensionArray.
```


### Issue Description

This issue is similar to #59177 and is coming from `pint-pandas` where test CI job with nightly builds from pandas was recently introduced ([pint-pandas issue related to skipped tests to pass tests with pandas 3](https://github.com/hgrecco/pint-pandas/issues/240)).

The above example is fine with pandas 2.2.2 but fails with pandas nightlies

The above mentionned `TypeError` is coming from https://github.com/pandas-dev/pandas/blob/ab433af410464f4f5c377c82a3d4f5680bf3c65c/pandas/core/algorithms.py#L222

As explained in #59177 `NumpyExtensionArray` may be used internally when other type of `ExtensionArray` are not available.

### Expected Behavior

for pandas 2.2.2 `pd.unique` returns:

``` python
>>> pd.unique(arr_complex)
array([1.+1.j, 2.+0.j, 3.+0.j])
```

While we expect

```python
>>> pd.unique(arr_complex)
<NumpyExtensionArray>
[(1+1j), (2+0j), (3+0j)]
Length: 3, dtype: complex128
```

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59213/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59213/timeline,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/59212,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59212/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59212/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59212/events,https://github.com/pandas-dev/pandas/issues/59212,2396391937,I_kwDOAA0YD86O1goB,59212,BUG: regression in master for DataFrame.sparse.from_spmatrix,"{'login': 'bmreiniger', 'id': 40676050, 'node_id': 'MDQ6VXNlcjQwNjc2MDUw', 'avatar_url': 'https://avatars.githubusercontent.com/u/40676050?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bmreiniger', 'html_url': 'https://github.com/bmreiniger', 'followers_url': 'https://api.github.com/users/bmreiniger/followers', 'following_url': 'https://api.github.com/users/bmreiniger/following{/other_user}', 'gists_url': 'https://api.github.com/users/bmreiniger/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bmreiniger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bmreiniger/subscriptions', 'organizations_url': 'https://api.github.com/users/bmreiniger/orgs', 'repos_url': 'https://api.github.com/users/bmreiniger/repos', 'events_url': 'https://api.github.com/users/bmreiniger/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bmreiniger/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-08T19:26:47Z,2024-07-08T19:27:19Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
from scipy.sparse import eye
from pandas import DataFrame
DataFrame.sparse.from_spmatrix(eye(5))
```


### Issue Description

(This bug **does not** exist on the latest version of pandas, but that checkbox was required to submit the issue.)

In main branch, the example produces a frame with entries 1.0 and NaN (sparse, with `fill_value` nan).

PR #59064 corrected a bug for other dtypes, but introduced this regression for float dtype.

### Expected Behavior

In latest version (2.2.2) and earlier, produces a frame with entries 1.0 and 0.0 (sparse, with `fill_value` 0).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 69fe98dda091cae71ea699be3f44926406851a2c
python                : 3.12.4
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 3.0.0.dev0+1170.g69fe98dda
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : 3.9.0
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.2.2
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59212/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59212/timeline,,
3,https://api.github.com/repos/pandas-dev/pandas/issues/59211,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59211/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59211/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59211/events,https://github.com/pandas-dev/pandas/pull/59211,2396085734,PR_kwDOAA0YD850uC-h,59211,BUG: .plot(kind='pie') with ArrowDtype,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzMzI4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization', 'name': 'Visualization', 'color': '8AE234', 'default': False, 'description': 'plotting'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': 'pyarrow functionality'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 47, 'closed_issues': 1029, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2024-07-08T23:33:03Z', 'due_on': None, 'closed_at': None}",0,2024-07-08T16:37:25Z,2024-07-08T18:14:43Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59211', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59211', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59211.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59211.patch', 'merged_at': None}",- [ ] closes #59192 (Replace xxxx with the GitHub issue number),"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59211/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59211/timeline,,
4,https://api.github.com/repos/pandas-dev/pandas/issues/59210,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59210/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59210/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59210/events,https://github.com/pandas-dev/pandas/pull/59210,2396011434,PR_kwDOAA0YD850tyzL,59210,CLN: More read_csv state,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 47, 'closed_issues': 1029, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2024-07-08T23:33:03Z', 'due_on': None, 'closed_at': None}",0,2024-07-08T15:58:58Z,2024-07-08T17:05:30Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59210', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59210', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59210.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59210.patch', 'merged_at': None}",Also inlines some single use methods/functions,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59210/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59210/timeline,,
5,https://api.github.com/repos/pandas-dev/pandas/issues/59207,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59207/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59207/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59207/events,https://github.com/pandas-dev/pandas/issues/59207,2394929953,I_kwDOAA0YD86Ov7sh,59207,"ENH: Extend to_numeric to Convert Hexadecimal, Octal, and Binary Strings with Prefixes","{'login': 'beci', 'id': 936184, 'node_id': 'MDQ6VXNlcjkzNjE4NA==', 'avatar_url': 'https://avatars.githubusercontent.com/u/936184?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/beci', 'html_url': 'https://github.com/beci', 'followers_url': 'https://api.github.com/users/beci/followers', 'following_url': 'https://api.github.com/users/beci/following{/other_user}', 'gists_url': 'https://api.github.com/users/beci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/beci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/beci/subscriptions', 'organizations_url': 'https://api.github.com/users/beci/orgs', 'repos_url': 'https://api.github.com/users/beci/repos', 'events_url': 'https://api.github.com/users/beci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/beci/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,"{'login': 'AnaDenisa', 'id': 24620565, 'node_id': 'MDQ6VXNlcjI0NjIwNTY1', 'avatar_url': 'https://avatars.githubusercontent.com/u/24620565?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AnaDenisa', 'html_url': 'https://github.com/AnaDenisa', 'followers_url': 'https://api.github.com/users/AnaDenisa/followers', 'following_url': 'https://api.github.com/users/AnaDenisa/following{/other_user}', 'gists_url': 'https://api.github.com/users/AnaDenisa/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AnaDenisa/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AnaDenisa/subscriptions', 'organizations_url': 'https://api.github.com/users/AnaDenisa/orgs', 'repos_url': 'https://api.github.com/users/AnaDenisa/repos', 'events_url': 'https://api.github.com/users/AnaDenisa/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AnaDenisa/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'AnaDenisa', 'id': 24620565, 'node_id': 'MDQ6VXNlcjI0NjIwNTY1', 'avatar_url': 'https://avatars.githubusercontent.com/u/24620565?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AnaDenisa', 'html_url': 'https://github.com/AnaDenisa', 'followers_url': 'https://api.github.com/users/AnaDenisa/followers', 'following_url': 'https://api.github.com/users/AnaDenisa/following{/other_user}', 'gists_url': 'https://api.github.com/users/AnaDenisa/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AnaDenisa/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AnaDenisa/subscriptions', 'organizations_url': 'https://api.github.com/users/AnaDenisa/orgs', 'repos_url': 'https://api.github.com/users/AnaDenisa/repos', 'events_url': 'https://api.github.com/users/AnaDenisa/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AnaDenisa/received_events', 'type': 'User', 'site_admin': False}]",,1,2024-07-08T08:00:34Z,2024-07-08T16:15:31Z,,NONE,,,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

Extend the pandas.to_numeric function to support the conversion of strings representing hexadecimal, octal, and binary numbers when they start with the corresponding prefixes (0x, 0o, 0b).

```python
s = pd.Series([""1.0"", ""2"", -3, ""0x32""])
pd.to_numeric(s)  # , errors=""coerce"")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File lib.pyx:2391, in pandas._libs.lib.maybe_convert_numeric()

ValueError: Unable to parse string ""0x32""

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[39], [line 2](vscode-notebook-cell:?execution_count=39&line=2)
      [1](vscode-notebook-cell:?execution_count=39&line=1) s = pd.Series([""1.0"", ""2"", -3, ""0x32""])
----> [2](vscode-notebook-cell:?execution_count=39&line=2) pd.to_numeric(s)  # , errors=""coerce"")

File oSDH5rfs-py3.11\Lib\site-packages\pandas\core\tools\numeric.py:232, in to_numeric(arg, errors, downcast, dtype_backend)
    [230](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:230) coerce_numeric = errors not in (""ignore"", ""raise"")
    [231](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:231) try:
--> [232](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:232)     values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
    [233](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:233)         values,
    [234](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:234)         set(),
    [235](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:235)         coerce_numeric=coerce_numeric,
    [236](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:236)         convert_to_masked_nullable=dtype_backend is not lib.no_default
    [237](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:237)         or isinstance(values_dtype, StringDtype)
    [238](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:238)         and not values_dtype.storage == ""pyarrow_numpy"",
    [239](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:239)     )
    [240](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:240) except (ValueError, TypeError):
    [241](file:///oSDH5rfs-py3.11/Lib/site-packages/pandas/core/tools/numeric.py:241)     if errors == ""raise"":

File lib.pyx:2433, in pandas._libs.lib.maybe_convert_numeric()

ValueError: Unable to parse string ""0x32"" at position 3
```

### Feature Description

pandas.to_numeric is a versatile function for converting various data types to numeric values. However, it currently does not support the direct conversion of strings representing numbers in different bases (hexadecimal, octal, and binary) that use standard prefixes. Adding this feature would enhance the function's utility and align it with the conversion capabilities found in core Python functions and PEP standards.

Modify the pandas.to_numeric function to detect strings starting with 0x (hexadecimal), 0o (octal), and 0b (binary) and convert them to their corresponding integer values.


- Hexadecimal Strings:
  - Prefix: `0x` or `0X`
  - Example: `0x1A` should convert to `26`.
- Octal Strings:
  - Prefix: `0o` or `0O`
  - Example: `0o32` should convert to `26`.
- Binary Strings:
  - Prefix: `0b` or `0B`
  - Example: `0b11010` should convert to `26`.

### Alternative Solutions

```python
import pandas as pd

def extended_to_numeric(series):
    def convert_value(value):
        if isinstance(value, str):
            if value.startswith(('0x', '0X')):
                return int(value, 16)
            elif value.startswith(('0o', '0O')):
                return int(value, 8)
            elif value.startswith(('0b', '0B')):
                return int(value, 2)
        return pd.to_numeric(value, errors='coerce')
    
    return series.apply(convert_value)

# Example usage
data = pd.Series(['0x1A', '0o32', '0b11010', '42', 'invalid'])
numeric_data = extended_to_numeric(data)
print(numeric_data)
```

### Additional Context

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59207/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59207/timeline,,
6,https://api.github.com/repos/pandas-dev/pandas/issues/59205,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59205/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59205/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59205/events,https://github.com/pandas-dev/pandas/pull/59205,2394458920,PR_kwDOAA0YD850od5m,59205,ENH: dt.day_of_week should return int8,"{'login': 'rmhowe425', 'id': 45905457, 'node_id': 'MDQ6VXNlcjQ1OTA1NDU3', 'avatar_url': 'https://avatars.githubusercontent.com/u/45905457?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rmhowe425', 'html_url': 'https://github.com/rmhowe425', 'followers_url': 'https://api.github.com/users/rmhowe425/followers', 'following_url': 'https://api.github.com/users/rmhowe425/following{/other_user}', 'gists_url': 'https://api.github.com/users/rmhowe425/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rmhowe425/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rmhowe425/subscriptions', 'organizations_url': 'https://api.github.com/users/rmhowe425/orgs', 'repos_url': 'https://api.github.com/users/rmhowe425/repos', 'events_url': 'https://api.github.com/users/rmhowe425/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rmhowe425/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-08T02:26:36Z,2024-07-08T02:26:36Z,,CONTRIBUTOR,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59205', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59205', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59205.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59205.patch', 'merged_at': None}","- [X] closes #58185
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59205/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59205/timeline,,
7,https://api.github.com/repos/pandas-dev/pandas/issues/59197,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59197/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59197/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59197/events,https://github.com/pandas-dev/pandas/pull/59197,2393991299,PR_kwDOAA0YD850nCWD,59197,Pyarrow series .any() Error fixed,"{'login': 'Riyazul555', 'id': 121575277, 'node_id': 'U_kgDOBz8XbQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/121575277?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Riyazul555', 'html_url': 'https://github.com/Riyazul555', 'followers_url': 'https://api.github.com/users/Riyazul555/followers', 'following_url': 'https://api.github.com/users/Riyazul555/following{/other_user}', 'gists_url': 'https://api.github.com/users/Riyazul555/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Riyazul555/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Riyazul555/subscriptions', 'organizations_url': 'https://api.github.com/users/Riyazul555/orgs', 'repos_url': 'https://api.github.com/users/Riyazul555/repos', 'events_url': 'https://api.github.com/users/Riyazul555/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Riyazul555/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-07T10:28:16Z,2024-07-07T10:28:16Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59197', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59197', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59197.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59197.patch', 'merged_at': None}","- [ ] closes #59192  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59197/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59197/timeline,,
8,https://api.github.com/repos/pandas-dev/pandas/issues/59196,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59196/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59196/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59196/events,https://github.com/pandas-dev/pandas/issues/59196,2393772977,I_kwDOAA0YD86OrhOx,59196,BUG: ValueError when accessing dataFrame with array attribute,"{'login': 'Zybulon', 'id': 97910143, 'node_id': 'U_kgDOBdX9fw', 'avatar_url': 'https://avatars.githubusercontent.com/u/97910143?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Zybulon', 'html_url': 'https://github.com/Zybulon', 'followers_url': 'https://api.github.com/users/Zybulon/followers', 'following_url': 'https://api.github.com/users/Zybulon/following{/other_user}', 'gists_url': 'https://api.github.com/users/Zybulon/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Zybulon/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Zybulon/subscriptions', 'organizations_url': 'https://api.github.com/users/Zybulon/orgs', 'repos_url': 'https://api.github.com/users/Zybulon/repos', 'events_url': 'https://api.github.com/users/Zybulon/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Zybulon/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-06T22:52:44Z,2024-07-06T22:52:44Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np

attrs = {""A"": ""B"", ""G"": np.array([1.2, 2.4])}

# This one works
arr = np.random.rand(60, 1)
df_named = pd.DataFrame(arr)
df_named.attrs = attrs
print(df_named[0])

# This one works
arr = np.random.rand(61, 1)
df_named = pd.DataFrame(arr)
df_named.attrs = {""A"": ""B"", ""G"": ""A""}
print(df_named[0])

# This one does not works
arr = np.random.rand(61, 1)
df_named = pd.DataFrame(arr)
df_named.attrs = attrs
print(df_named)  # This works
print(df_named[0])  # This does not works
```


### Issue Description

Hello, 

I have a dataFrame of size (61,1) with 2 attributes (one is an array) and I can't print the first Serie of the DataFrame.
I have the following Error : 
```
Traceback (most recent call last):

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File d:\documents\perso\travail\mbda\pandas_extension\h5pandas\tests\debug.py:23
    print(df_named[0])  # This does not works

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\series.py:1784 in __repr__
    return self.to_string(**repr_params)

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\series.py:1871 in to_string
    formatter = fmt.SeriesFormatter(

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\io\formats\format.py:225 in __init__
    self._chk_truncate()

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\io\formats\format.py:247 in _chk_truncate
    series = concat((series.iloc[:row_num], series.iloc[-row_num:]))

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\reshape\concat.py:395 in concat
    return op.get_result()

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\reshape\concat.py:650 in get_result
    return result.__finalize__(self, method=""concat"")

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\generic.py:6273 in __finalize__
    have_same_attrs = all(obj.attrs == attrs for obj in other.objs[1:])

  File ~\miniforge-pypy3\envs\h5pandas_dev\Lib\site-packages\pandas\core\generic.py:6273 in <genexpr>
    have_same_attrs = all(obj.attrs == attrs for obj in other.objs[1:])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

However I can print the DataFrame, it does not raise the ValueError.
If the DataFrame hasn't got the array attribute, I do not have ValueError.
If the DataFrame has only 60 rows, I do not have ValueError.

### Expected Behavior

I should not have this ValueError.

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : en
LOCALE                : fr_FR.cp1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 70.1.1
pip                   : 24.0
Cython                : None
pytest                : 8.2.2
hypothesis            : None
sphinx                : 7.3.7
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.26.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : 0.22.0
tzdata                : 2024.1
qtpy                  : 2.4.1
pyqt5                 : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59196/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59196/timeline,,
9,https://api.github.com/repos/pandas-dev/pandas/issues/59193,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59193/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59193/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59193/events,https://github.com/pandas-dev/pandas/issues/59193,2393027517,I_kwDOAA0YD86OorO9,59193,ENH: Pipe `attrs` to_html Jinja2 environmental variables,"{'login': 'disarticulate', 'id': 17464125, 'node_id': 'MDQ6VXNlcjE3NDY0MTI1', 'avatar_url': 'https://avatars.githubusercontent.com/u/17464125?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/disarticulate', 'html_url': 'https://github.com/disarticulate', 'followers_url': 'https://api.github.com/users/disarticulate/followers', 'following_url': 'https://api.github.com/users/disarticulate/following{/other_user}', 'gists_url': 'https://api.github.com/users/disarticulate/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/disarticulate/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/disarticulate/subscriptions', 'organizations_url': 'https://api.github.com/users/disarticulate/orgs', 'repos_url': 'https://api.github.com/users/disarticulate/repos', 'events_url': 'https://api.github.com/users/disarticulate/events{/privacy}', 'received_events_url': 'https://api.github.com/users/disarticulate/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-05T19:01:11Z,2024-07-05T19:01:11Z,,NONE,,,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

Dataframe and Styler implement a ```.to_html``` function which allows using custom styles via jinja2 custom templates which can be accessed via ```https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.formats.style.Styler.from_custom_template.html```

Templates exposes each cell as a dict in the format of:
```
{'type': 'td', 'value': '0.004', 'class': 'data row3 col4', 'is_visible': True, 'attributes': '', 'display_value': '0.004', 'id': 'row3_col4'}
```
Dataframes and Series appear to implement the necessary but ???: 
```
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.attrs.html#pandas.DataFrame.attrs
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.attrs.html#pandas.Series.attrs
```

Though it's not clear these are the same things.

I'm trying to pipe a jupyter notebook to html, then from html pandoc it to Docx. This requires being able to set a ```attribute=value``` defined as ```custom-style=""Footnote Text""```, which allows Pandoc to apply a docx style.

### Feature Description

Figure out how to either add attributes from the series or dataframe or implement a Styler component which adds attributes which get put into the jinja2 template. It's clear this was intended, but not implemented.

### Alternative Solutions

The alternative would have me making custom templates for every table I need, rather than allowing pandoc to naturally adapt styles

### Additional Context

I could probably implement this feature but it's obfuscated how the render goes from accessing a cell and putting that into a render function.

I assume it can be a mirror image of the ```set_table_styles``` function and instead but ```set_table_attributes``` unless the intention was to use the ```Dataframe.attrs``` or ```Series.attrs```.

Either way, some clear direction could get this implemented.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59193/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59193/timeline,,
10,https://api.github.com/repos/pandas-dev/pandas/issues/59192,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59192/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59192/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59192/events,https://github.com/pandas-dev/pandas/issues/59192,2392957430,I_kwDOAA0YD86OoaH2,59192,"BUG: Pyarrow series .any() returns a bool, messing up plotting","{'login': 'JonPizza', 'id': 45501389, 'node_id': 'MDQ6VXNlcjQ1NTAxMzg5', 'avatar_url': 'https://avatars.githubusercontent.com/u/45501389?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JonPizza', 'html_url': 'https://github.com/JonPizza', 'followers_url': 'https://api.github.com/users/JonPizza/followers', 'following_url': 'https://api.github.com/users/JonPizza/following{/other_user}', 'gists_url': 'https://api.github.com/users/JonPizza/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JonPizza/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JonPizza/subscriptions', 'organizations_url': 'https://api.github.com/users/JonPizza/orgs', 'repos_url': 'https://api.github.com/users/JonPizza/repos', 'events_url': 'https://api.github.com/users/JonPizza/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JonPizza/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': 'pyarrow functionality'}]",open,False,,[],,0,2024-07-05T17:46:13Z,2024-07-08T16:31:22Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd

series = pd.Series([1, 2, 3, 4], dtype='int32[pyarrow]')

series.plot(kind='pie')
```


### Issue Description

The example yields this error:

```
Traceback (most recent call last):
  File ""/home/jon/work/panda.py"", line 5, in <module>
    series.plot(kind='pie')
  File ""/home/jon/.local/lib/python3.11/site-packages/pandas/plotting/_core.py"", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/jon/.local/lib/python3.11/site-packages/pandas/plotting/_matplotlib/__init__.py"", line 70, in plot
    plot_obj = PLOT_CLASSES[kind](data, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/jon/.local/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py"", line 2051, in __init__
    if (data < 0).any().any():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'any'
```

The error comes from `(data < 0).any()` giving a boolean (`<class 'bool'>`) instead of a numpy boolean (`<class 'numpy.bool_'>`). 

```
>>> series = pd.Series([1, 2, 3, 4], dtype='int32[pyarrow]')
>>> type((series < 0).any())
<class 'bool'>
>>> series = pd.Series([1, 2, 3, 4], dtype='int32')         
>>> type((series < 0).any())                       
<class 'numpy.bool_'>
```

When `.any()` is called on the numpy bool, it just returns the same value, but the AttributeError is raised when `.any()` is called on the boolean.

### Expected Behavior

This code does exactly what I want:

```py
import pandas as pd
import matplotlib.pyplot as plt

series = pd.Series([1, 2, 3, 4], dtype='int32[pyarrow]')

plt.pie(series)
```

and works, but I don't have direct control over the code as I'm using an LLM to write code and it still uses the `series.plot` feature. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.3.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.4.0-187-generic
Version               : #207-Ubuntu SMP Mon Jun 10 08:16:10 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.24.3
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 65.5.0
pip                   : 23.2.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : 2.9.7
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.7.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : 0.21.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59192/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59192/timeline,,
11,https://api.github.com/repos/pandas-dev/pandas/issues/59190,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59190/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59190/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59190/events,https://github.com/pandas-dev/pandas/pull/59190,2392774845,PR_kwDOAA0YD850jB57,59190,DataFrameGroupBy.agg with nan results error Fixed,"{'login': 'Riyazul555', 'id': 121575277, 'node_id': 'U_kgDOBz8XbQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/121575277?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Riyazul555', 'html_url': 'https://github.com/Riyazul555', 'followers_url': 'https://api.github.com/users/Riyazul555/followers', 'following_url': 'https://api.github.com/users/Riyazul555/following{/other_user}', 'gists_url': 'https://api.github.com/users/Riyazul555/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Riyazul555/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Riyazul555/subscriptions', 'organizations_url': 'https://api.github.com/users/Riyazul555/orgs', 'repos_url': 'https://api.github.com/users/Riyazul555/repos', 'events_url': 'https://api.github.com/users/Riyazul555/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Riyazul555/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-05T15:05:48Z,2024-07-06T07:48:30Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59190', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59190', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59190.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59190.patch', 'merged_at': None}","- [#59106 ] closes #59106  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59190/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59190/timeline,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/59189,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59189/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59189/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59189/events,https://github.com/pandas-dev/pandas/pull/59189,2392755723,PR_kwDOAA0YD850i9yQ,59189,DataFrame.eval error fixed,"{'login': 'Riyazul555', 'id': 121575277, 'node_id': 'U_kgDOBz8XbQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/121575277?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Riyazul555', 'html_url': 'https://github.com/Riyazul555', 'followers_url': 'https://api.github.com/users/Riyazul555/followers', 'following_url': 'https://api.github.com/users/Riyazul555/following{/other_user}', 'gists_url': 'https://api.github.com/users/Riyazul555/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Riyazul555/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Riyazul555/subscriptions', 'organizations_url': 'https://api.github.com/users/Riyazul555/orgs', 'repos_url': 'https://api.github.com/users/Riyazul555/repos', 'events_url': 'https://api.github.com/users/Riyazul555/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Riyazul555/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-05T14:53:29Z,2024-07-06T07:48:57Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59189', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59189', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59189.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59189.patch', 'merged_at': None}","- [#59062 ] closes #59062  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59189/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59189/timeline,,
13,https://api.github.com/repos/pandas-dev/pandas/issues/59188,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59188/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59188/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59188/events,https://github.com/pandas-dev/pandas/pull/59188,2392722488,PR_kwDOAA0YD850i2j4,59188,Difference between calamine and openpyxl readers fixed,"{'login': 'Riyazul555', 'id': 121575277, 'node_id': 'U_kgDOBz8XbQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/121575277?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Riyazul555', 'html_url': 'https://github.com/Riyazul555', 'followers_url': 'https://api.github.com/users/Riyazul555/followers', 'following_url': 'https://api.github.com/users/Riyazul555/following{/other_user}', 'gists_url': 'https://api.github.com/users/Riyazul555/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Riyazul555/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Riyazul555/subscriptions', 'organizations_url': 'https://api.github.com/users/Riyazul555/orgs', 'repos_url': 'https://api.github.com/users/Riyazul555/repos', 'events_url': 'https://api.github.com/users/Riyazul555/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Riyazul555/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-05T14:32:26Z,2024-07-07T18:08:00Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59188', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59188', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59188.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59188.patch', 'merged_at': None}","- [ #59186 ] closes #59186  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59188/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59188/timeline,,
14,https://api.github.com/repos/pandas-dev/pandas/issues/59187,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59187/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59187/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59187/events,https://github.com/pandas-dev/pandas/issues/59187,2392677257,I_kwDOAA0YD86OnVuJ,59187,BUG: merge_asof on float does not detect float equality,"{'login': 'RaphaelRosset', 'id': 51163660, 'node_id': 'MDQ6VXNlcjUxMTYzNjYw', 'avatar_url': 'https://avatars.githubusercontent.com/u/51163660?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RaphaelRosset', 'html_url': 'https://github.com/RaphaelRosset', 'followers_url': 'https://api.github.com/users/RaphaelRosset/followers', 'following_url': 'https://api.github.com/users/RaphaelRosset/following{/other_user}', 'gists_url': 'https://api.github.com/users/RaphaelRosset/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RaphaelRosset/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RaphaelRosset/subscriptions', 'organizations_url': 'https://api.github.com/users/RaphaelRosset/orgs', 'repos_url': 'https://api.github.com/users/RaphaelRosset/repos', 'events_url': 'https://api.github.com/users/RaphaelRosset/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RaphaelRosset/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-05T14:05:00Z,2024-07-05T14:05:59Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
left_df = pd.DataFrame({""CONTINUOUS"": list(np.arange(100.0, 106.0, 0.8))})
data = [
    (98.0, 103.4, ""A"", ""a""),
    (104.0, 106.8, ""B"", ""b""),
]
right_df = pd.DataFrame(data, columns=[""START"", ""END"", ""C1"", ""C2""])
output = pd.merge_asof(
    left_df.sort_values(by=""CONTINUOUS""),
    right_df.sort_values(by=""START""),
    left_on=""CONTINUOUS"",
    right_on=""START"",
    direction=""backward"",
)
print(output.to_string())
```


### Issue Description

When merge_asof is done with On key being a float number sometimes error due to float precision issue can be seen

   CONTINUOUS  START    END C1
0       100.0   98.0  103.4  A
1       100.8   98.0  103.4  A
2       101.6   98.0  103.4  A
3       102.4   98.0  103.4  A
4       103.2   98.0  103.4  A
5       104.0   98.0  103.4  A   <=== 104.0 mapped to A is wrong
6       104.8  104.0  106.8  B
7       105.6  104.0  106.8  B



Note that changing the way CONTINOUS list of values is created makes the output as expected.
For example on my side, these 2 alternative give correct output.
[103.2, 104.0, 104.8] ==> correct output
list(np.arange(103.2, 106.0, 0.8)) ==> correct output

### Expected Behavior

   CONTINUOUS  START    END C1
0       100.0   98.0  103.4  A
1       100.8   98.0  103.4  A
2       101.6   98.0  103.4  A
3       102.4   98.0  103.4  A
4       103.2   98.0  103.4  A
5       104.0   98.0  103.4  B   <=== 104.0 mapped to B is correct
6       104.8  104.0  106.8  B
7       105.6  104.0  106.8  B


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.2.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : Norwegian Bokmål_Norway.1252

pandas                : 2.2.2
numpy                 : 2.0.0
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.1.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59187/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59187/timeline,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/59186,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59186/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59186/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59186/events,https://github.com/pandas-dev/pandas/issues/59186,2392318894,I_kwDOAA0YD86Ol-Ou,59186,BUG: Difference between calamine and openpyxl readers - columns with mixed data types,"{'login': 'asishm', 'id': 1978117, 'node_id': 'MDQ6VXNlcjE5NzgxMTc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1978117?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/asishm', 'html_url': 'https://github.com/asishm', 'followers_url': 'https://api.github.com/users/asishm/followers', 'following_url': 'https://api.github.com/users/asishm/following{/other_user}', 'gists_url': 'https://api.github.com/users/asishm/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/asishm/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/asishm/subscriptions', 'organizations_url': 'https://api.github.com/users/asishm/orgs', 'repos_url': 'https://api.github.com/users/asishm/repos', 'events_url': 'https://api.github.com/users/asishm/events{/privacy}', 'received_events_url': 'https://api.github.com/users/asishm/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2024-07-05T10:22:55Z,2024-07-07T18:02:22Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import datetime

df = pd.DataFrame({'a': ['abc', np.nan, datetime.now(), 'def']})

out = BytesIO()
df.to_excel(out, index=False)
df_openpyxl = pd.read_excel(out, engine='openpyxl')
df_calamine = pd.read_excel(out, engine='calamine')

In [49]: df_openpyxl['a'].map(type)
Out[49]:
0                  <class 'str'>
1                <class 'float'>
2    <class 'datetime.datetime'>
3                  <class 'str'>
Name: a, dtype: object

In [50]: df_calamine['a'].map(type)
Out[50]:
0                                        <class 'str'>
1                                      <class 'float'>
2    <class 'pandas._libs.tslibs.timestamps.Timesta...
3                                        <class 'str'>
Name: a, dtype: object
```


### Issue Description

When trying to read an excel file that has mixed formats, using the calamine engine - results in an object dtype column where the value is `pandas._libs.tslibs.timestamps.Timestamp` and `pandas._libs.tslibs.timedeltas.Timedelta` whereas with the openpyxl engine, these values are `datetime.datetime` and `datetime.timedelta` instead.

The difference seems to be because the calamine implementation explicitly sets `pd.Timestamp/pd.Timedelta` data types
https://github.com/pandas-dev/pandas/blob/79067a76adc448d17210f2cf4a858b0eb853be4c/pandas/io/excel/_calamine.py#L109-L115

whereas the openpyxl implementation uses whatever the library returns.

### Expected Behavior

The individual item data types should match

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : dd87dd3ef661ac06e30adc55d25a1f03deda3abf
python                : 3.10.14
python-bits           : 64
OS                    : Linux
OS-release            : 4.19.128-microsoft-standard
Version               : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 3.0.0.dev0+1113.gdd87dd3ef6
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0
pip                   : 24.0
Cython                : 3.0.10
sphinx                : 7.3.7
IPython               : 8.25.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.3.8
fastparquet           : 2024.5.0
fsspec                : 2024.6.0
html5lib              : 1.1
hypothesis            : 6.103.0
gcsfs                 : 2024.6.0
jinja2                : 3.1.4
lxml.etree            : 5.2.2
matplotlib            : 3.8.4
numba                 : 0.59.1
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : 3.1.2
psycopg2              : 2.9.9
pymysql               : 1.4.6
pyarrow               : 16.1.0
pyreadstat            : 1.2.7
pytest                : 8.2.1
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2024.6.0
scipy                 : 1.13.1
sqlalchemy            : 2.0.30
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2024.5.0
xlrd                  : 2.0.1
xlsxwriter            : 3.1.9
zstandard             : 0.19.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59186/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59186/timeline,,
16,https://api.github.com/repos/pandas-dev/pandas/issues/59182,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59182/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59182/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59182/events,https://github.com/pandas-dev/pandas/issues/59182,2390958375,I_kwDOAA0YD86OgyEn,59182,ENH: check_dtype='equiv' for assert_frame_equal in unit testing,"{'login': 'levaphenyl', 'id': 29597341, 'node_id': 'MDQ6VXNlcjI5NTk3MzQx', 'avatar_url': 'https://avatars.githubusercontent.com/u/29597341?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/levaphenyl', 'html_url': 'https://github.com/levaphenyl', 'followers_url': 'https://api.github.com/users/levaphenyl/followers', 'following_url': 'https://api.github.com/users/levaphenyl/following{/other_user}', 'gists_url': 'https://api.github.com/users/levaphenyl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/levaphenyl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/levaphenyl/subscriptions', 'organizations_url': 'https://api.github.com/users/levaphenyl/orgs', 'repos_url': 'https://api.github.com/users/levaphenyl/repos', 'events_url': 'https://api.github.com/users/levaphenyl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/levaphenyl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-04T14:05:06Z,2024-07-04T14:05:06Z,,NONE,,,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

My test fails because the data cast and expected data have slightly different types, like `int32` vs. `int64`. 
I don't want to use `assert_frame_equal(df1, df2, check_dtype=False)` because it does not check the data type at all, which is bad.

```python
import pandas as pd


a = pd.DataFrame({'Int': [1, 2, 3], 'Float': [0.57, 0.179, 0.213]})  # Automatic type casting
# Force 32-bit
b = a.copy()
b['Int'] = b['Int'].astype('int32')
b['Float'] = b['Float'].astype('float32')
# Force 64-bit
c = a.copy()
c['Int'] = c['Int'].astype('int64')
c['Float'] = c['Float'].astype('float64')
try:
    pd.testing.assert_frame_equal(b, c)
    print('Success')
except AssertionError as err:
    print(err)
```

gives

```
Attributes of DataFrame.iloc[:, 0] (column name=""Int"") are different

Attribute ""dtype"" are different
[left]:  int32
[right]: int64
```

### Feature Description

Something like `assert_frame_equal(df1, df2, check_dtype='equiv')` would be handy but it does not work because the function uses the hard check of [`assert_attr_equal`](https://github.com/pandas-dev/pandas/blob/2.2.x/pandas/_testing/asserters.py#L386) under the hood.

It means changing the logic to either have a soft attribute check in `assert_attr_equal`, or call a new function if the `check_dtype` is set to `'equiv'`.

### Alternative Solutions

I added a workaround function to my unit tests, which casts the data type of one DataFrame to the other when the types are similar (int, float).

```python
def assert_frame_equiv(left: pd.DataFrame, right: pd.DataFrame) -> None:
    """"""Convert equivalent data types to same before comparing.

    Parameters
    ----------
    left : DataFrame
        First DataFrame to compare.
    right : DataFrame
        Second DataFrame to compare.

    Raises
    ------
    AssertionError
        If the DataFrames are different.
    """"""
    # First, check that the columns are the same.
    pd.testing.assert_index_equal(left.columns, right.columns, check_order=False)
    # Knowing columns names are the same, cast the same data type if equivalent.
    for col_name in left.columns:
        lcol = left[col_name]
        rcol = right[col_name]
        if (
            (pd.api.types.is_integer_dtype(lcol) and pd.api.types.is_integer_dtype(rcol))
            or (pd.api.types.is_float_dtype(lcol) and pd.api.types.is_float_dtype(rcol))
        ):
            left[col_name] = lcol.astype(rcol.dtype)

    return pd.testing.assert_frame_equal(left, right, check_like=True)
```

### Additional Context

Adapted from my [answer on SO](https://stackoverflow.com/a/78707389/8289769).

Thanks for making `pandas`!","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59182/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59182/timeline,,
17,https://api.github.com/repos/pandas-dev/pandas/issues/59179,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59179/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59179/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59179/events,https://github.com/pandas-dev/pandas/pull/59179,2390269605,PR_kwDOAA0YD850aikg,59179,DEPR: group by one element list gets scalar keys,"{'login': 'natmokval', 'id': 91160475, 'node_id': 'MDQ6VXNlcjkxMTYwNDc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/91160475?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/natmokval', 'html_url': 'https://github.com/natmokval', 'followers_url': 'https://api.github.com/users/natmokval/followers', 'following_url': 'https://api.github.com/users/natmokval/following{/other_user}', 'gists_url': 'https://api.github.com/users/natmokval/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/natmokval/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/natmokval/subscriptions', 'organizations_url': 'https://api.github.com/users/natmokval/orgs', 'repos_url': 'https://api.github.com/users/natmokval/repos', 'events_url': 'https://api.github.com/users/natmokval/events{/privacy}', 'received_events_url': 'https://api.github.com/users/natmokval/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-04T08:29:34Z,2024-07-08T14:09:13Z,,CONTRIBUTOR,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59179', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59179', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59179.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59179.patch', 'merged_at': None}","- [x] closes #58858

changed the behavior: group `keys` to be `1-tuples` instead of `scalar` when grouping with a `length-1 list`","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59179/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59179/timeline,,
18,https://api.github.com/repos/pandas-dev/pandas/issues/59178,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59178/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59178/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59178/events,https://github.com/pandas-dev/pandas/pull/59178,2389601483,PR_kwDOAA0YD850YRtV,59178,PERF: Don't create a CategoricalIndex._engine in __contains__ if categories are RangeIndex,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 47, 'closed_issues': 1029, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2024-07-08T23:33:03Z', 'due_on': None, 'closed_at': None}",0,2024-07-03T22:31:21Z,2024-07-05T17:14:52Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59178', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59178', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59178.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59178.patch', 'merged_at': None}",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59178/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59178/timeline,,
19,https://api.github.com/repos/pandas-dev/pandas/issues/59173,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59173/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59173/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59173/events,https://github.com/pandas-dev/pandas/pull/59173,2387298263,PR_kwDOAA0YD850QXhx,59173,TST: Added script to enforce usage of match argument for tm.assert_produces_warning ,"{'login': 'chaarvii', 'id': 49508554, 'node_id': 'MDQ6VXNlcjQ5NTA4NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/49508554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chaarvii', 'html_url': 'https://github.com/chaarvii', 'followers_url': 'https://api.github.com/users/chaarvii/followers', 'following_url': 'https://api.github.com/users/chaarvii/following{/other_user}', 'gists_url': 'https://api.github.com/users/chaarvii/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chaarvii/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chaarvii/subscriptions', 'organizations_url': 'https://api.github.com/users/chaarvii/orgs', 'repos_url': 'https://api.github.com/users/chaarvii/repos', 'events_url': 'https://api.github.com/users/chaarvii/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chaarvii/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2024-07-02T22:56:09Z,2024-07-05T23:54:06Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59173', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59173', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59173.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59173.patch', 'merged_at': None}","xref #58290 

Added a script called `enforce_match_arg_in_assert_produces_warning.py` which checks that all usages of tm.assert_produces_warning make use of the `match` argument. This is done to ensure that users are always displayed the correct warning message. Uses of `tm.assert_produces_warning(None)` have been excluded as no warning is produced in this case. 

Furthermore, to ensure that the existing code doesn't fail the `pre-commit` stage, all files that currently do not use the match argument have been excluded. 
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59173/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59173/timeline,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/59172,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59172/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59172/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59172/events,https://github.com/pandas-dev/pandas/pull/59172,2387214979,PR_kwDOAA0YD850QFF0,59172,REF: Move methods in core/reshape/util.py to where they are used,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 47, 'closed_issues': 1029, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2024-07-08T23:33:03Z', 'due_on': None, 'closed_at': None}",0,2024-07-02T21:41:58Z,2024-07-05T17:56:20Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59172', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59172', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59172.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59172.patch', 'merged_at': None}",2 unit tests were removed since `cartesian_product` now strictly operates on `list[np.ndarray]` (i.e. `MultiIndex.codes`) and the unit tests were testing `Index` inputs,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59172/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59172/timeline,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/59170,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59170/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59170/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59170/events,https://github.com/pandas-dev/pandas/issues/59170,2386867431,I_kwDOAA0YD86ORLTn,59170,BUG: ,"{'login': 'seanv507', 'id': 3305775, 'node_id': 'MDQ6VXNlcjMzMDU3NzU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3305775?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/seanv507', 'html_url': 'https://github.com/seanv507', 'followers_url': 'https://api.github.com/users/seanv507/followers', 'following_url': 'https://api.github.com/users/seanv507/following{/other_user}', 'gists_url': 'https://api.github.com/users/seanv507/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/seanv507/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/seanv507/subscriptions', 'organizations_url': 'https://api.github.com/users/seanv507/orgs', 'repos_url': 'https://api.github.com/users/seanv507/repos', 'events_url': 'https://api.github.com/users/seanv507/events{/privacy}', 'received_events_url': 'https://api.github.com/users/seanv507/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-07-02T18:14:35Z,2024-07-02T18:16:57Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
z3 = pd.DataFrame({""a"":[10], ""b"":[2], ""c"": [1]}).set_index([""a"", ""b""])
maturities = list(range(100))
z4 = z3.reindex(maturities,level=1)
```


### Issue Description

I create a 1 row dataframe with multiindex
I reindex on a single level, and I expect all values in the new index to be in the new dataframe.
instead, the same dataframe is returned.

the same happens with more than a single row.

If I use a 1d index, or apply to the columns, I get a 100 row/column dataframe as expected

### Expected Behavior

```
expected_output = pd.DataFrame({""a"":10, ""b"": range(100), ""c"": np.nan}).set_index([""a"", ""b""])
expected_output.loc[(10,2), ""c""]=1

expected_output.head()
#          c
# a  b     
# 10 0  NaN
#    1  NaN
#    2  1.0
#    3  NaN
#    4  NaN
```
### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.5.0
Version             : Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59170/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59170/timeline,,
22,https://api.github.com/repos/pandas-dev/pandas/issues/59165,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59165/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59165/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59165/events,https://github.com/pandas-dev/pandas/issues/59165,2385272154,I_kwDOAA0YD86OLF1a,59165,"ENH: In pd.cut(), allow bins='auto' (leveraging `np.histogram_bin_edges`)","{'login': 'Hari-Shankar-Karthik', 'id': 143477305, 'node_id': 'U_kgDOCI1KOQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/143477305?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Hari-Shankar-Karthik', 'html_url': 'https://github.com/Hari-Shankar-Karthik', 'followers_url': 'https://api.github.com/users/Hari-Shankar-Karthik/followers', 'following_url': 'https://api.github.com/users/Hari-Shankar-Karthik/following{/other_user}', 'gists_url': 'https://api.github.com/users/Hari-Shankar-Karthik/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Hari-Shankar-Karthik/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Hari-Shankar-Karthik/subscriptions', 'organizations_url': 'https://api.github.com/users/Hari-Shankar-Karthik/orgs', 'repos_url': 'https://api.github.com/users/Hari-Shankar-Karthik/repos', 'events_url': 'https://api.github.com/users/Hari-Shankar-Karthik/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Hari-Shankar-Karthik/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1639305834, 'node_id': 'MDU6TGFiZWwxNjM5MzA1ODM0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/cut', 'name': 'cut', 'color': '9aace2', 'default': False, 'description': 'cut, qcut'}]",open,False,"{'login': 'chaarvii', 'id': 49508554, 'node_id': 'MDQ6VXNlcjQ5NTA4NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/49508554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chaarvii', 'html_url': 'https://github.com/chaarvii', 'followers_url': 'https://api.github.com/users/chaarvii/followers', 'following_url': 'https://api.github.com/users/chaarvii/following{/other_user}', 'gists_url': 'https://api.github.com/users/chaarvii/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chaarvii/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chaarvii/subscriptions', 'organizations_url': 'https://api.github.com/users/chaarvii/orgs', 'repos_url': 'https://api.github.com/users/chaarvii/repos', 'events_url': 'https://api.github.com/users/chaarvii/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chaarvii/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'chaarvii', 'id': 49508554, 'node_id': 'MDQ6VXNlcjQ5NTA4NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/49508554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chaarvii', 'html_url': 'https://github.com/chaarvii', 'followers_url': 'https://api.github.com/users/chaarvii/followers', 'following_url': 'https://api.github.com/users/chaarvii/following{/other_user}', 'gists_url': 'https://api.github.com/users/chaarvii/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chaarvii/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chaarvii/subscriptions', 'organizations_url': 'https://api.github.com/users/chaarvii/orgs', 'repos_url': 'https://api.github.com/users/chaarvii/repos', 'events_url': 'https://api.github.com/users/chaarvii/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chaarvii/received_events', 'type': 'User', 'site_admin': False}]",,3,2024-07-02T05:31:40Z,2024-07-07T14:57:03Z,,NONE,,,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

While converting a quantitative variable into a qualitative one, `pd.cut()` comes in clutch. However, it requires the user to specify `bins` as either an integer or a list of bin edges. I wish it was allowed to specify `bins='auto'` similar to how `np.histogram` allows it. It internally leverages `np.histogram_bin_edges` to compute these. Thank you.

### Expectation
Instead of coding 
`pd.cut(df['x1'], bins=np.histogram_bin_edges(df['x1'], bins='auto'))`
Allow for coding
`pd.cut(df['x1'], bins='auto')`

### Additional Context

Calculation of bin edges is already done via `np.histogram_bin_edges`. Reference: https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html#numpy-histogram-bin-edges","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59165/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59165/timeline,,
23,https://api.github.com/repos/pandas-dev/pandas/issues/59164,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59164/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59164/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59164/events,https://github.com/pandas-dev/pandas/issues/59164,2385092809,I_kwDOAA0YD86OKaDJ,59164,DOC: Sort the pandas API reference navbar in alphabetical order,"{'login': 'jeropaul', 'id': 520985, 'node_id': 'MDQ6VXNlcjUyMDk4NQ==', 'avatar_url': 'https://avatars.githubusercontent.com/u/520985?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jeropaul', 'html_url': 'https://github.com/jeropaul', 'followers_url': 'https://api.github.com/users/jeropaul/followers', 'following_url': 'https://api.github.com/users/jeropaul/following{/other_user}', 'gists_url': 'https://api.github.com/users/jeropaul/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jeropaul/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jeropaul/subscriptions', 'organizations_url': 'https://api.github.com/users/jeropaul/orgs', 'repos_url': 'https://api.github.com/users/jeropaul/repos', 'events_url': 'https://api.github.com/users/jeropaul/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jeropaul/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}]",open,False,,[],,2,2024-07-02T03:03:42Z,2024-07-04T12:31:27Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

### Documentation problem

The navigation bar in the API reference documentation is not sorted in alphabetical order!

current navigation example order copied directly from the page.

Dataframe
  pandas.DataFrame
  pandas.DataFrame.index
  pandas.DataFrame.columns
  pandas.DataFrame.dtypes
  pandas.DataFrame.info
  pandas.DataFrame.select_dtypes
  pandas.DataFrame.values
  pandas.DataFrame.axes
  pandas.DataFrame.ndim
  pandas.DataFrame.size
  pandas.DataFrame.shape
  pandas.DataFrame.memory_usage
  pandas.DataFrame.empty

Why is this a problem?

As a developer starting to work with Python and Pandas
When reviewing the Pandas API reference docs
Then it is really easy to miss behaviour that I would want to use, because of how it is sorted 

### Suggested fix for documentation

Sort the documentation alphabetically.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59164/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59164/timeline,,
24,https://api.github.com/repos/pandas-dev/pandas/issues/59163,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59163/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59163/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59163/events,https://github.com/pandas-dev/pandas/issues/59163,2384575350,I_kwDOAA0YD86OIbt2,59163,ENH: Add Option to Include Array Offset as MultiIndex Level in `explode()`,"{'login': 'chelsea-lin', 'id': 124939984, 'node_id': 'U_kgDOB3Ju0A', 'avatar_url': 'https://avatars.githubusercontent.com/u/124939984?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/chelsea-lin', 'html_url': 'https://github.com/chelsea-lin', 'followers_url': 'https://api.github.com/users/chelsea-lin/followers', 'following_url': 'https://api.github.com/users/chelsea-lin/following{/other_user}', 'gists_url': 'https://api.github.com/users/chelsea-lin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/chelsea-lin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/chelsea-lin/subscriptions', 'organizations_url': 'https://api.github.com/users/chelsea-lin/orgs', 'repos_url': 'https://api.github.com/users/chelsea-lin/repos', 'events_url': 'https://api.github.com/users/chelsea-lin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/chelsea-lin/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,"{'login': 'ritwizsinha', 'id': 43509699, 'node_id': 'MDQ6VXNlcjQzNTA5Njk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/43509699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ritwizsinha', 'html_url': 'https://github.com/ritwizsinha', 'followers_url': 'https://api.github.com/users/ritwizsinha/followers', 'following_url': 'https://api.github.com/users/ritwizsinha/following{/other_user}', 'gists_url': 'https://api.github.com/users/ritwizsinha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ritwizsinha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ritwizsinha/subscriptions', 'organizations_url': 'https://api.github.com/users/ritwizsinha/orgs', 'repos_url': 'https://api.github.com/users/ritwizsinha/repos', 'events_url': 'https://api.github.com/users/ritwizsinha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ritwizsinha/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'ritwizsinha', 'id': 43509699, 'node_id': 'MDQ6VXNlcjQzNTA5Njk5', 'avatar_url': 'https://avatars.githubusercontent.com/u/43509699?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ritwizsinha', 'html_url': 'https://github.com/ritwizsinha', 'followers_url': 'https://api.github.com/users/ritwizsinha/followers', 'following_url': 'https://api.github.com/users/ritwizsinha/following{/other_user}', 'gists_url': 'https://api.github.com/users/ritwizsinha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ritwizsinha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ritwizsinha/subscriptions', 'organizations_url': 'https://api.github.com/users/ritwizsinha/orgs', 'repos_url': 'https://api.github.com/users/ritwizsinha/repos', 'events_url': 'https://api.github.com/users/ritwizsinha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ritwizsinha/received_events', 'type': 'User', 'site_admin': False}]",,7,2024-07-01T19:22:04Z,2024-07-08T17:15:49Z,,NONE,,,,"### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

Currently, `df.explode()` and `s.explode()` flatten lists/arrays within Series/DataFrames. However, information about the original position of each element within its list is lost. This makes it difficult to:

- Easily access specific sub-values after exploding.
- Reconstruct the original nested structure if needed.

**Proposed Solution:**
Introduce a new parameter, `offset`, to both `df.explode()` and `s.explode()`.

**Example Usage:**

```
>>> s = pd.Series([[1, 2, 3], 'foo', [], [3, 4]])
>>> s
0    [1, 2, 3]
1          foo
2           []
3       [3, 4]
dtype: object
>>> s.explode() # <- Current behavior:
0         1
0         2
0         3
1       foo
2       NaN
3         3
3         4
dtype: object

>>> s.explode(offset=True) # <- With proposed feature
0  1         1
   2         2
   3         3
1  1       foo
2  1       NaN
3  1         3
   2         4
dtype: object
```



### Feature Description

Introduce a new parameter, `offset`, to both `df.explode()` and `s.explode()`.
```
def explode(self, ..., offset: bool = False):  # Default to False for backward compatibility
    """"""
    Parameters:
        ...
        offset: If True, include the original array offset as a level in the resulting MultiIndex.
    """"""
```

### Alternative Solutions

While it's technically possible to infer the offset in some cases, it requires additional steps and assumptions about the data. The offset parameter provides a direct, intuitive solution.

### Additional Context

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59163/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59163/timeline,,
25,https://api.github.com/repos/pandas-dev/pandas/issues/59161,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59161/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59161/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59161/events,https://github.com/pandas-dev/pandas/issues/59161,2384536291,I_kwDOAA0YD86OISLj,59161,DEPR: `keep_default_dates` and  `convert_dates` in `read_json`,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}, {'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON', 'name': 'IO JSON', 'color': '207de5', 'default': False, 'description': 'read_json, to_json, json_normalize'}, {'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate', 'name': 'Deprecate', 'color': '5319e7', 'default': False, 'description': 'Functionality to remove in pandas'}]",open,False,,[],,0,2024-07-01T18:56:53Z,2024-07-01T18:57:14Z,,MEMBER,,,,"`read_json` has `convert_dates`, `keep_default_dates` and `dtypes` that all try to perform dtype conversions on the result from the ujson parser. Conflicts can arise when a column matching the specification of `keep_default_dates` matches a column specified in `dtypes`.

The proposal is to deprecate `keep_default_dates` and `convert_dates` and only use `dtype`'s current definition of

* `True`: attempt dtype conversion on all column (and refactor to use `infer_dtype` instead of `astype` guessing)
* `False`: perform no dtype conversion
* `dict`: dict keys that match column labels will be cast to type in the dict value","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59161/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59161/timeline,,
26,https://api.github.com/repos/pandas-dev/pandas/issues/59160,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59160/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59160/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59160/events,https://github.com/pandas-dev/pandas/issues/59160,2384469816,I_kwDOAA0YD86OIB84,59160,VOTE: Voting issue for PDEP-14: Dedicated string data type for pandas 3.0 ,"{'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}","[{'id': 5732441949, 'node_id': 'LA_kwDOAA0YD88AAAABVa4fXQ', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Vote', 'name': 'Vote', 'color': '4D0D12', 'default': False, 'description': 'Used to track votes issues for PDEPs'}]",open,True,,[],,12,2024-07-01T18:23:19Z,2024-07-06T01:26:43Z,,MEMBER,,,,"### PDEP number and title

PDEP-14: Dedicated string data type for pandas 3.0

### Pull request with discussion

#58551

### Rendered PDEP for easy reading

https://jorisvandenbossche.github.io/pandas-website-preview/pdeps/0014-string-dtype.html

### Discussion participants

_No response_

### Voting will close in 15 days.

July 16

### Vote

Cast your vote in a comment below.
* +1: approve.
* 0: abstain.
    * Reason: A one sentence reason is required.
* -1: disapprove
    * Reason: A one sentence reason is required.
A disapprove vote requires prior participation in the linked discussion PR.

@pandas-dev/pandas-core
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59160/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59160/timeline,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/59157,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59157/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59157/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59157/events,https://github.com/pandas-dev/pandas/pull/59157,2384264965,PR_kwDOAA0YD850F-87,59157,"header, update in basic.rst M #59130","{'login': 'BadakalaYashwanth', 'id': 170221536, 'node_id': 'U_kgDOCiVf4A', 'avatar_url': 'https://avatars.githubusercontent.com/u/170221536?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/BadakalaYashwanth', 'html_url': 'https://github.com/BadakalaYashwanth', 'followers_url': 'https://api.github.com/users/BadakalaYashwanth/followers', 'following_url': 'https://api.github.com/users/BadakalaYashwanth/following{/other_user}', 'gists_url': 'https://api.github.com/users/BadakalaYashwanth/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/BadakalaYashwanth/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/BadakalaYashwanth/subscriptions', 'organizations_url': 'https://api.github.com/users/BadakalaYashwanth/orgs', 'repos_url': 'https://api.github.com/users/BadakalaYashwanth/repos', 'events_url': 'https://api.github.com/users/BadakalaYashwanth/events{/privacy}', 'received_events_url': 'https://api.github.com/users/BadakalaYashwanth/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-07-01T16:33:42Z,2024-07-01T17:39:43Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59157', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59157', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59157.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59157.patch', 'merged_at': None}","closes #59130
![Screenshot 2024-07-01 220007](https://github.com/pandas-dev/pandas/assets/170221536/3f95dbd5-2ac2-4cf8-9a51-80ba62d536f6)
By changing the header to ""With speedup (ms)"" and ""Without speedup (ms)"", the documentation will directly highlight the performance improvements. This makes it easier for users to understand the value of these libraries without needing to know about older versions.

.. csv-table::
    :header: ""Operation"", ""With speedup (ms)"", ""Without speedup (ms)"", ""Ratio""
    :widths: 25, 25, 25, 25

    ``df1 > df2``, 13.32, 125.35,  0.1063
    ``df1 * df2``, 21.71,  36.63,  0.5928
    ``df1 + df2``, 22.04,  36.50,  0.6039
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59157/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59157/timeline,,
28,https://api.github.com/repos/pandas-dev/pandas/issues/59153,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59153/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59153/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59153/events,https://github.com/pandas-dev/pandas/issues/59153,2383186357,I_kwDOAA0YD86ODIm1,59153,BUG: Enlarging multilevel index fails if one or more level keys are None,"{'login': 'micky-gee', 'id': 25528701, 'node_id': 'MDQ6VXNlcjI1NTI4NzAx', 'avatar_url': 'https://avatars.githubusercontent.com/u/25528701?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/micky-gee', 'html_url': 'https://github.com/micky-gee', 'followers_url': 'https://api.github.com/users/micky-gee/followers', 'following_url': 'https://api.github.com/users/micky-gee/following{/other_user}', 'gists_url': 'https://api.github.com/users/micky-gee/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/micky-gee/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/micky-gee/subscriptions', 'organizations_url': 'https://api.github.com/users/micky-gee/orgs', 'repos_url': 'https://api.github.com/users/micky-gee/repos', 'events_url': 'https://api.github.com/users/micky-gee/events{/privacy}', 'received_events_url': 'https://api.github.com/users/micky-gee/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2024-07-01T08:25:20Z,2024-07-02T07:40:27Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd

#Create simple multilevel index with two levels (note one entry on level 1 is None):
index = pd.MultiIndex.from_tuples([('A', 'a1'), ('A', 'a2'), ('B', 'b1'), ('B', None)])

#Create dataframe with said index:
pd.DataFrame([(0, 6), (1, 5), (2, 4), (3, 7)], index=index)

#       0  1
#A a1   0  6
#  a2   1  5
#B b1   2  4
#  NaN  3  7

#Now it is possible to enlarge this dataframe with a new index entry provided none of the keys are None:
df.loc[('B', 'b2'),:] = [10, 11]

#           0     1
# A a1    0.0   6.0
#   a2    1.0   5.0
# B b1    2.0   4.0
#   NaN   3.0   7.0
#   b2   10.0  11.0

#However this will throw a KeyError:
df.loc[('A', None),:] = [12, 13]

#Also doesn't work with an index slice:
idx = pd.IndexSlice

#this will throw a KeyError:
df.loc[idx['A', None],:] = [12, 13]
```


### Issue Description

It is possible to enlarge a dataframe with a multilevel indexes by providing the new key as parameters to df.loc[...]

It is also possible to create entries to multilevel indices that have None as the key i.e. df.loc[('A', None),...]

It is *not* possible to enlarge a dataframe with a multilevel index if one or more of the keys is None.

### Expected Behavior

Building on the example above, 
`df.loc[('A', None),:] = [12, 13]`

should result in the following:
```#           0     1
# A a1    0.0   6.0
#   a2    1.0   5.0
#   NaN  12.0  13.0
# B b1    2.0   4.0
#   NaN   3.0   7.0
#   b2   10.0  11.0
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.10.6.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.5.0
Version               : Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 63.2.0
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : 0.59.1
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59153/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59153/timeline,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/59151,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59151/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59151/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59151/events,https://github.com/pandas-dev/pandas/pull/59151,2382495796,PR_kwDOAA0YD85z_7Ea,59151,Add a New form of using pd.eval(),"{'login': 'PedroVerardo', 'id': 99936353, 'node_id': 'U_kgDOBfToYQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/99936353?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/PedroVerardo', 'html_url': 'https://github.com/PedroVerardo', 'followers_url': 'https://api.github.com/users/PedroVerardo/followers', 'following_url': 'https://api.github.com/users/PedroVerardo/following{/other_user}', 'gists_url': 'https://api.github.com/users/PedroVerardo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/PedroVerardo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/PedroVerardo/subscriptions', 'organizations_url': 'https://api.github.com/users/PedroVerardo/orgs', 'repos_url': 'https://api.github.com/users/PedroVerardo/repos', 'events_url': 'https://api.github.com/users/PedroVerardo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/PedroVerardo/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-06-30T23:24:22Z,2024-06-30T23:24:22Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59151', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59151', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59151.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59151.patch', 'merged_at': None}","- [x] closes #56491
- [x] Tests added and passed( We just modify some testes)
- [ ] contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations]
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

That is not the best solution because we are unfamiliar with the parsing library and classes. However, we managed to understand the variables that needed to change. With some help, we can solve the problem more accurately.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59151/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59151/timeline,,
